# Generated by Django 4.1.5 on 2023-01-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=120)),
                ('photo', models.ImageField(default='null', upload_to='')),
                ('birthday', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type_options', models.CharField(choices=[(0, 'Móvil'), (1, 'Casa')], default=0, max_length=10)),
                ('alias', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactos.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('exterior_number', models.CharField(max_length=10)),
                ('internal_number', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('state', models.IntegerField(choices=[(0, 'SELECCIONAR'), (1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Coahuila'), (6, 'Colima'), (7, 'Chiapas'), (8, 'Chihuahua'), (9, 'Ciudad de México'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'México'), (16, 'Michoacán'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0)),
                ('references', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactos.contact')),
            ],
        ),
    ]
